# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef8723e070e5fd639aac49b2ea528304387a69edd029db4decdeb5724c443235f93272d23698136b3edfe6fc7663fa30fa974e6a3dd69ccc55f85ef4a94bfbe7

test:
  secret_key_base: 55aa8c9b8ee54396b6523d64e082b73312dae4a436e9ab5010fb29e866e001ab68728b941b2d62fac1b704d22205e98c4768b33d5e39aa49d48763286386c0ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
